import {
  MistralLogo,
  OpenAILogo,
  GeminiLogo,
  AwsLogo,
  AzureLogo,
  AnthropicLogo,
  GroqLogo,
  FireworksLogo,
  DeepseekLogo,
  CohereLogo,
  OllamaLogo,
  XaiLogo,
  AgnoIcon,
  UserIcon,
  AgentIcon,
  SheetIcon,
  NextjsTag,
  ShadcnTag,
  TailwindTag,
  AgnoTag,
  ReasoningIcon,
  ReferencesIcon
} from './custom-icons'
import { IconTypeMap } from './types'
import {
  RefreshCw,
  Edit,
  Save,
  X,
  ArrowDown,
  SendIcon,
  Download,
  HammerIcon,
  Check,
  ChevronDown,
  ChevronUp,
  Trash,
  // New icons for UX enhancements
  Copy,
  Square,
  Sparkles,
  Zap,
  Crown,
  MessageSquare,
  Keyboard,
  Wifi,
  WifiOff,
  AlertCircle,
  Clock,
  Captions,
  Palette,
  // Quick action icons
  Video,
  Mic,
  Music,
  Play,
  Eye,
  Type,
  Wand2
} from 'lucide-react'

import { PlusIcon } from '@radix-ui/react-icons'

export const ICONS: IconTypeMap = {
  'open-ai': OpenAILogo,
  mistral: MistralLogo,
  gemini: GeminiLogo,
  aws: AwsLogo,
  azure: AzureLogo,
  anthropic: AnthropicLogo,
  groq: GroqLogo,
  fireworks: FireworksLogo,
  deepseek: DeepseekLogo,
  cohere: CohereLogo,
  ollama: OllamaLogo,
  xai: XaiLogo,
  agno: AgnoIcon,
  user: UserIcon,
  agent: AgentIcon,
  sheet: SheetIcon,
  nextjs: NextjsTag,
  shadcn: ShadcnTag,
  tailwind: TailwindTag,
  reasoning: ReasoningIcon,
  'agno-tag': AgnoTag,
  refresh: RefreshCw,
  edit: Edit,
  save: Save,
  x: X,
  'arrow-down': ArrowDown,
  send: SendIcon,
  download: Download,
  hammer: HammerIcon,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'plus-icon': PlusIcon,
  references: ReferencesIcon,
  trash: Trash,
  // New icons for UX enhancements
  copy: Copy,
  stop: Square,
  sparkles: Sparkles,
  zap: Zap,
  crown: Crown,
  'message-square': MessageSquare,
  keyboard: Keyboard,
  wifi: Wifi,
  'wifi-off': WifiOff,
  'alert-circle': AlertCircle,
  clock: Clock,
  subtitles: Captions,
  palette: Palette,
  // Quick action icons
  video: Video,
  mic: Mic,
  music: Music,
  play: Play,
  eye: Eye,
  type: Type,
  wand: Wand2
}
