-- Enable pgvector extension for vector similarity search
-- This migration adds embedding support for assets using Twelve Labs

BEGIN;

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding column (1024 dimensions for Twelve Labs Marengo model)
ALTER TABLE octupost.assets 
ADD COLUMN IF NOT EXISTS embedding vector(1024);

-- Create index for similarity search using IVFFlat
-- Note: IVFFlat requires at least some data to build the index effectively
-- For production with large datasets, consider HNSW index instead
CREATE INDEX IF NOT EXISTS idx_assets_embedding 
ON octupost.assets USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Add a comment for documentation
COMMENT ON COLUMN octupost.assets.embedding IS 'Multimodal embedding vector (1024 dimensions) generated by Twelve Labs Marengo model';

COMMIT;
