-- Create persistent jobs table for tracking generation jobs
-- Replaces in-memory job store with Supabase-backed storage
-- Enables Realtime for instant frontend updates

BEGIN;

-- =============================================================================
-- Jobs Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS octupost.jobs (
  id TEXT PRIMARY KEY,  -- ULID from backend
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,  -- 'text-to-image', 'text-to-video', 'avatar', 'text-to-speech', etc.
  status TEXT NOT NULL DEFAULT 'pending' 
    CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'cancelled')),
  progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  
  -- Request info (for display/retry)
  model TEXT NOT NULL,
  params JSONB,
  
  -- Result info
  asset_id UUID REFERENCES octupost.assets(id) ON DELETE SET NULL,
  result JSONB,
  error TEXT,
  
  -- Credit tracking
  credits_estimated INTEGER,
  credits_actual INTEGER,
  reservation_id TEXT,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- Indexes for common queries
-- =============================================================================

-- Primary query for playground: user's jobs by type and status
CREATE INDEX IF NOT EXISTS idx_jobs_owner_type_status 
  ON octupost.jobs(owner_id, type, status, created_at DESC);

-- Query for active jobs (pending/processing)
CREATE INDEX IF NOT EXISTS idx_jobs_owner_active 
  ON octupost.jobs(owner_id, created_at DESC) 
  WHERE status IN ('pending', 'processing');

-- Lookup by asset_id
CREATE INDEX IF NOT EXISTS idx_jobs_asset_id 
  ON octupost.jobs(asset_id) 
  WHERE asset_id IS NOT NULL;

-- =============================================================================
-- Updated_at trigger
-- =============================================================================
CREATE OR REPLACE FUNCTION octupost.update_jobs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER jobs_updated_at_trigger
  BEFORE UPDATE ON octupost.jobs
  FOR EACH ROW
  EXECUTE FUNCTION octupost.update_jobs_updated_at();

-- =============================================================================
-- RLS Policies
-- =============================================================================
ALTER TABLE octupost.jobs ENABLE ROW LEVEL SECURITY;

-- Users can view their own jobs
CREATE POLICY "Users can view own jobs"
  ON octupost.jobs FOR SELECT
  USING (auth.uid() = owner_id);

-- Users can insert their own jobs (though typically done via service role)
CREATE POLICY "Users can insert own jobs"
  ON octupost.jobs FOR INSERT
  WITH CHECK (auth.uid() = owner_id);

-- Service role has full access for backend operations
CREATE POLICY "Service role full access jobs"
  ON octupost.jobs FOR ALL
  USING (auth.role() = 'service_role');

-- Dev policy for development (matches existing pattern)
CREATE POLICY "dev_jobs_all" 
  ON octupost.jobs FOR ALL TO authenticated 
  USING (true) 
  WITH CHECK (true);

-- =============================================================================
-- Enable Realtime
-- =============================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE octupost.jobs;

-- =============================================================================
-- Comments
-- =============================================================================
COMMENT ON TABLE octupost.jobs IS 'Persistent job tracking for AI generation tasks. Supports Realtime subscriptions for instant frontend updates.';
COMMENT ON COLUMN octupost.jobs.id IS 'ULID generated by backend';
COMMENT ON COLUMN octupost.jobs.type IS 'Generation type: text-to-image, text-to-video, image-to-video, avatar, text-to-speech, text-to-music, text-to-audio';
COMMENT ON COLUMN octupost.jobs.status IS 'Job status: pending, processing, completed, failed, cancelled';
COMMENT ON COLUMN octupost.jobs.progress IS 'Progress percentage 0-100';
COMMENT ON COLUMN octupost.jobs.params IS 'Original generation parameters (prompt, model settings, etc.)';
COMMENT ON COLUMN octupost.jobs.result IS 'Generation result (URL, metadata) on success';
COMMENT ON COLUMN octupost.jobs.error IS 'Error message on failure';

COMMIT;

